import './globals.css'
import type { Metadata } from "next";
import React from "react";
import Navbar from "@/app/components/navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'min-h-screen w-screen flex flex-col'}>
        <Navbar />
        <main className={'grow'}>
          {children}
        </main>
        <footer className={'p-6 bg-black text-white'}>
          © Created by Ethan Schwartz
        </footer>
      </body>
    </html>
  );
}
