import './globals.css'
import type { Metadata } from "next";
import React from "react";
import Navbar from "@/app/components/navbar";


export const metadata: Metadata = {
  title: "Next.js Template By Ethan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'dark min-h-screen w-screen flex flex-col'}>
        <Navbar />
        <main className={'grow'}>
          {children}
        </main>
        <footer className={'flex justify-between p-6 bg-black text-white'}>
          <span>© Created by Ethan Schwartz</span>
          <a href="https://master.d1jrnlwppmxg2k.amplifyapp.com/" className={'group flex items-center gap-2 text-sm font-mono'}>
            <span className={'group-hover:underline underline-offset-4'}>Check out my Nuxt template</span>
            <i className={'fi fi-rr-arrow-right flex items-center'}></i>
          </a>
        </footer>
      </body>
    </html>
  );
}
